name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  sshkey:
    name: install shkey
    runs-on: ubuntu-latest
    steps:
      # See https://zellwk.com/blog/github-actions-deploy/
      - name: install SSH key for mongo tunnel for tests
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    needs: sshkey
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.7'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          JENKINS_USER: rooty
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          SSH_OPTS: -i$HOME/.ssh/github-actions
  docs:
    name: Documentation
    needs: sshkey
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build and deploy documdents
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          JENKINS_USER: rooty
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
          SSH_OPTS: -i$HOME/.ssh/github-actions

        run: |
          echo SSH_OPTS is $SSH_OPTS2
          julia --project=docs/ docs/make.jl
          # SSH_OPTS="-i$HOME/.ssh/github-actions" julia --project=docs/ docs/make.jl

      # - run: |
      #     julia --project=docs -e '
      #       using Documenter: DocMeta, doctest
      #       using Pilr
      #       DocMeta.setdocmeta!(Pilr, :DocTestSetup, :(using Pilr); recursive=true)
      #       doctest(Packrat)'
