name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      # See https://zellwk.com/blog/github-actions-deploy/
      - name: install SSH key for mongo tunnel for tests
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Build and deploy
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
          SSH_OPTS2: -i$HOME/.ssh/github-actions

        run: |
          echo SSH_OPTS2 is $SSH_OPTS2
          SSH_OPTS="-i$HOME/.ssh/github-actions" julia --project=docs/ docs/make.jl
