# This is a basic workflow to help you get started with Actions

name: SSH Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # See https://zellwk.com/blog/github-actions-deploy/
      - name: install SSH key for mongo tunnel for tests
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          JENKINS_USER: rooty
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
          SSH_OPTS:  ${{ format('-i{0}/.ssh/github-actions', env.HOME) }}
        run: |
          echo SSH_OPTS is "$SSH_OPTS"
          ssh -i$HOME/.ssh/github-actions rooty@jenkins.pilrhealth.com touch GITHUBACTION
